export type BioEvent = {
  A?: string;
  pers_name?: string;
  event_type?: string;
  pers_function?: string;
  pers_title?: string;
  inst_name?: string;
  event_start?: string;
  "event_after-date"?: string;
  "event_before-date"?: string;
  event_end?: string;
  factoid_ID?: string;
  alternative_names?: string;
  pers_ID?: string;
  rel_pers?: string;
  source_quotations?: string;
  additional_info?: string;
  comment?: string;
  info_dump?: string;
  source_combined?: string;
  event_value?: string;
  place_name?: string;
  address?: string;
  suffix?: string;
  community?: string;
  region_1?: string;
  region_2?: string;
  continent?: string;
  addresses_full?: string;
  ids?: string;
  "geonames address"?: string;
  latitudes?: string;
  longitudes?: string;
  lat?: string;
  lng?: string;
  "Google address"?: string;
};
